### ISSUE TITLE
create-react-app fails at creating a production build with react-fontawesome

### ISSUE THREAD

**Issue by diligiant** [FortAwesome/react-fontawesome#1]
Before I dive in, has anyone faced this issue / solved it?

```Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/@fortawesome/react-fontawesome/index.js:14

Read more here: http://bit.ly/2tRViJ9
```
I am using latest create-react-app configs and r-fa master.

**Comment by robmadole** [comment]
I think this is `camelcase`. I've had trouble with that package for a long time with things like this. Let me see if switching to `humps` would fix this.

**Comment by diligiant** [comment]
@robmadole it does. Thank you for the tip. While searching, I upgraded rollup config to work with 0.50, generate 3 libs (ump, es & cjs). Would you like me to PR it?

**Comment by robmadole** [comment]
@diligiant does it make sense to include a UMD version of this lib? I don't know that anyone would use it that way. But the ES module would be good to start (I assume you would use this and that's why you are willing to put in the work). If you want to PR that change against the new 0.0.8 we'll merge that.

**Comment by diligiant** [comment]
@robmadole Today's config already outputs a umd. Important react component (like react-router) output all 3 and as it's a line of config, I never overthink that ;)
