### ISSUE TITLE
TypeScript declaration file not found

### ISSUE THREAD

**Issue by roboslone** [FortAwesome/react-fontawesome#111]
I have these packages installed:
```
    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-common-types": "^0.1.3",
    "@fortawesome/fontawesome-free-solid": "^5.0.9",
    "@fortawesome/react-fontawesome": "^0.0.18",
```

But when I try this:
```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
```

I get following error:
```
(3,33): error TS7016: Could not find a declaration file for module '@fortawesome/react-fontawesome'. '<...>/node_modules/@fortawesome/react-fontawesome/index.js' implicitly has an 'any' type.
```

Is there an example usage of `react-fontawesome` with TS?

**Comment by roboslone** [comment]
`prerelease` versions seem to work if I also install `@fortawesome/fontawesome-svg-core` though.

**Comment by kirkbross** [comment]
I'm having the same issue. I found a type file but it's for a different react-fontawesome and I have the official react-fontawesome in my project.

**Comment by robmadole** [comment]
Hey there,

We currently have some pre-release candidates out (we are calling them 5.1.0) that address some of the issues that you've been having.

We are doing the work (and documentation) on the `development` branch:

https://github.com/FortAwesome/react-fontawesome/tree/development

Would you be willing to give this a try? Check out the UPGRADING.md for detailed instructions.

Also remember that since this is a pre-release you need to use NPM tag `@prerelease` like:

```
$ npm i --save @fortawesome/fontawesome-svg-core@prerelease
```

Please let us know how the upgrade goes and if you run into any problems. We are working hard to get the 5.1.0 release stabilized.

**Comment by EQuimper** [comment]
@robmadole I just try your pre release version. All good :)

**Comment by robmadole** [comment]
Awesome!

**Comment by sant123** [comment]
Works great! Thank you!
