### ISSUE TITLE
How to use with pro license?

### ISSUE THREAD

**Issue by lehresman** [FortAwesome/react-fontawesome#16]
I want to use the pro RC3 in React.  This library seems like the right choice, but it looks like it's designed only for the free version.  How can I add my pro icon packs and have them recognized by this library?  Is that supported yet?

**Comment by alexyaseen** [comment]
I was able to copy /packages from the repo into my project, and then import /project/fontawesome-pro-<style> in the same manner they recommend importing fontawesome-free-<style>

**Comment by raisedadead** [comment]
The usage docs have been updated:
https://fontawesome.com/how-to-use/use-with-node-js

**Comment by robmadole** [comment]
Gonna close. Let me know if you have any problems or questions.

**Comment by leotm** [comment]
Even after following the [docs](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers) and reading these threads, I've spent a couple hours figuring out how to get this working, because it's not clear.

To anybody else stumbling across this, what you have to do is also install `@fortawesome/pro-solid-svg-icons`, and just [use](https://fontawesome.com/how-to-use/on-the-web/using-with/react), then use as usual.

Nowhere online can I find instructions that you must replace:
`@fortawesome/FREE-solid-svg-icons`
with
`@fortawesome/PRO-solid-svg-icons`.

**Comment by corysimmons** [comment]
@robmadole Docs are overcomplicated. No idea why it takes 30 pages of extensive docs to explain how to use an icon set.

Please hire someone who uses Pro Fontawesome with React to write easy docs for this...

**Comment by jfairley** [comment]
It's a shame that the docs instruct us to install `@fortawesome/fontawesome-pro` then show no instructions on how to use it.

If you crack open `node_modules/@fortawesome/fontawesome-pro/js`, you'll see that all the icons are in there, but I too cannot find anything on the proper way to import from it.

**Comment by Jamil-Bailony** [comment]
I guess that too @jfairley , as till this moment there is no docs for `@fortawesome/fontawesome-free` and `@fortawesome/fontawesome-pro`
