### ISSUE TITLE
Could not find icon {prefix: "fas", iconName: "thumbs-up"}

### ISSUE THREAD

**Issue by marcoalmeidap** [FortAwesome/react-fontawesome#187]
Hi, 

I added the following code from your examples in the index.js file of an React 16 app:

```
  import { library } from '@fortawesome/fontawesome-svg-core';
  import { faThumbsUp } from '@fortawesome/pro-regular-svg-icons';
  library.add(faThumbsUp);
```

Then , I used the thumbs-up icon in a component: 

```
import PropTypes from 'prop-types';
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const PostActionSection = props => {
    const {showComments} = props;
    return (
        <div className="row mt-5">
            <div className="col-md-12">
                Icon: <FontAwesomeIcon icon="thumbs-up" />
            </div>
        </div>
    );
};
```

And the following error showed up:

**Could not find icon {prefix: "fas", iconName: "thumbs-up"}**

To test, I replaced the import pro-regular-svg-icons by pro-solid-svg-icons in the index.js file, and the problem was solved. But, I need the same icon for regular and light styles.

**Comment by ryanshores** [comment]
I was having the same problem with the free regular icons too. After googling it looks like the prefix `fas` is the default. If you figure out the correct prefix for the pro icon library you can change icon to be `icon={["prefix", "iconName"]}`. 

The regular and solid icons have different prefixes so that helps you with the other issue you mentioned. Just make sure you import both.

**Comment by foolishneo** [comment]
if you are importing icons from the regular set, you have to set the prefix to "far"

**Comment by NishargShah** [comment]
Replace

<FontAwesomeIcon icon="iconName"/>

with

<FontAwesomeIcon icon={iconName}/>
