### ISSUE TITLE
How to add color "primary" as Material Icons inbuilt support

### ISSUE THREAD

**Issue by sandeepmeenuga** [FortAwesome/react-fontawesome#239]
Thanks for wonderful package.

How to add color "primary" as Material Icons inbuilt support.
Eg: 
<AccountCircle color="primary"/>

I can ask you in another way, Can I use "theme" object in FontAwesomeIcon component, which helps to sync with MaterialUI in broader way.

**Comment by robmadole** [comment]
@sandeepmeenuga I'm not sure how Material Icons or MaterialUI related to Font Awesome? Can you explain further?

**Comment by thorn0** [comment]
Currently, https://material-ui.com/components/icons/ recommends using the font version of Font Awesome. Given how popular Material UI is, there has to exist a beautiful way to use the two libraries together. Nesting `FontAwesomeIcon` in `SvgIcon` seems to work but looks awkward. Also `SvgIcon` uses a square viewport by default. Because of that e.g. FA icons `cogs` and `users` aren't scaled the same way.
