### ISSUE TITLE
500 errors with private NPM repo `npm.fontawesome.com`

### ISSUE THREAD

**Issue by ekilah** [FortAwesome/react-fontawesome#331]
**Is your feature request related to a problem? Please describe.**
Occasionally (most recently, today), our project's deploys and builds will fail with 500 errors like this:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-brands-svg-icons/-/free-brands-svg-icons-5.10.1.tgz: Request failed \"500 Internal Server Error\"".
```
or
```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/pro-light-svg-icons-5.10.1.tgz: Request failed \"500 Internal Server Error\"".
```

**Describe the solution you'd like**
It would be great if we could self-host these files for use with this React plugin, so our project's deploys aren't affected by downtimes with your self-hosted NPM registry. Not being able to deploy changes to our site because of external dependency issues is not something we want to continue dealing with where possible.

**Describe alternatives you've considered**
n/a

**Additional context**
This happens occasionally, I last contacted `hello@fontawesome.com` on February 4th, 2020 - the last time I noticed this happening, and was told this:

> Very sorry for the issue. Our service provider is aware of this and is working on a fix now. You can go here to keep track: https://status.fortawesome.com. Yes, you can host Font Awesome yourself like this: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself.

However, when I clarified we were using the React plugin, the response was that self-hosting is not an option with this plugin.

**Comment by robmadole** [comment]
@ekilah the 500 errors were coming from Amazon's CloudFront product. [We posted the incident yesterday](https://status.fortawesome.com/incidents/7z2kqysn1r27).

The reason you got the response about self-hosting not being an option is because these are NPM packages. If you would like to self-host the packages you'll need to come up with a way that NPM can install your package without being online I'm assuming. [There are ways you can do this](https://www.google.com/search?client=safari&rls=en&q=offline+npm+repository&ie=UTF-8&oe=UTF-8).

I'm going to close this issue as it's not directly related to this React component.
