### ISSUE TITLE
change secondary color on Duotone icons

### ISSUE THREAD

**Issue by Rawnly** [FortAwesome/react-fontawesome#350]
**Is your feature request related to a problem? Please describe.**
I would like to have an option on `<FontAwesomeIcon />` to set the secondary color of a Duotone icon

**Describe the solution you'd like**
```jsx
<FontAwesomeIcon color='black' secondary='white' />

{/* OR */}
<FontAwesomeIcon colors={['black', 'white']} />
```

**Comment by robmadole** [comment]
Hi @Rawnly. It's important to us that custom CSS properties remain firmly in the CSS realm. Since Duotone icon opacity and color are configured this way we'll resist pretty strongly any additional properties that diverge from just using CSS.

I know that's probably not the answer you were wanting but I'm pretty stubborn about this one (it's been asked a few times!)

**Comment by Rawnly** [comment]
Ok! No problem! 👍
