### ISSUE TITLE
faWhale and faElephant not found

### ISSUE THREAD

**Issue by lordvee** [FortAwesome/react-fontawesome#498]
Hey

if i try to import faWhale and/or faElephant, they don't appear to exist, whereas the web site lists them in @fortawesome/free-solid-svg-icons 5.15.3

Here is the link:
https://fontawesome.com/v5/icons/elephant?s=solid
https://fontawesome.com/v5/icons/whale?s=solid

How can i import them? all other icons so far import fine

thanks

**Comment by robmadole** [comment]
@lordvee how are you trying to import them? Can you share the error message?

**Comment by lordvee** [comment]
Hi

the error is

`Attempted import error: 'faWhale' is not exported from '@fortawesome/free-solid-svg-icons' (imported as 'faWhale').`

I import it like every other icon:

```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faWhale, faFighterJet, faHeadset, faHandPointRight, faBook, faHippo, faDog, faShoePrints, faKiwiBird, faEnvelope, faPhone, faLifeRing } from '@fortawesome/free-solid-svg-icons'

And use it like so:

`<FontAwesomeIcon icon={faWhale} className="iconPrimary" size="2x" />`


thanks!
```

**Comment by robmadole** [comment]
@lordvee can you tell us how your project is setup? Are you using React Create App? Next.js?

**Comment by lordvee** [comment]
Hi,

This is a gatsby project. Is this the info you are looking for?

cheers :)

**Comment by kangetsu121** [comment]
@lordvee 
Hi, I found `faElephant` and `faWhale` icons are for Pro, so we cannot use them with `@fortawesome/free-solid-svg-icons` since it's free.
You can know they are Pro Icons by seeing ":rocket: Start Using This __Pro__ Icon" on these pages, so you need to upgrade your license to Pro to use these icons.

- <https://fontawesome.com/v5/icons/elephant?s=solid>
- <https://fontawesome.com/v5/icons/whale?s=solid>

I think it's helpful to filter icons by checking the box "Free" on the left side of search pages if you need to use only free icons.
By filtering, you can also know elephant and whale icons are not free because they don't appear on the search result.

I hope this info could help you, thank you.

**Comment by yadavshubham01** [comment]
@lordvee  @robmadole 
please assign me

**Comment by lordvee** [comment]
The isse was due to the icon being part of the non-free bundle
