### ISSUE TITLE
unused imports in icon-types.ts in kit (urgent/critical)

### ISSUE THREAD

**Issue by niborium** [FortAwesome/react-fontawesome#557]
**Describe the bug**
Hello,
We use fontawesome kit according to docs https://fontawesome.com/docs/web/use-with/react/.
When we try to build with vite & tcs we get following error.
![tsc error](https://github.com/FortAwesome/react-fontawesome/assets/88037608/97da5924-7e98-474c-b30a-e5f79156e0ca)

All imports in import declaration is unused.

node_modules/@awesome.me/kit_example/icons/modules/icon-types.ts

Line 2 is unused imports Icon & IconParams are not used..

Can you please remove you unused imports from icon-types.ts and release a fix for this?

**Reproducible test case**
Not needed, you can try this yourself and run tsc with linting rules and you will see you get this error.
If you are not using imports (unused) please remove them. If companies not have proper linting/tsc setup maybe precommit linting or proper config setup it make break build scripts etc.

**Expected behavior**
We should be able to run tsc without haven broken/unused imports in your library.

**Desktop (please complete the following information):**

- Version

**Additional context**

**Comment by rivaridley** [comment]
I am also running into this issue using a font awesome kit in a react project:

<img width="805" alt="image" src="https://github.com/FortAwesome/react-fontawesome/assets/99371685/f153855a-b7d5-49df-937d-f8f33cf781eb">

This is blocking us from switching over to using FA Kits. +1 to removing this unused import on line 2 of `icon-types.ts`.

**Comment by justinvforvendetta** [comment]
seems this repo isnt active anymore, am i wrong? was looking for the bluesky logo, but i see no ones done anything here for a few years, npm says 2 years since a release

**Comment by niborium** [comment]
> seems this repo isnt active anymore, am i wrong? was looking for the bluesky logo, but i see no ones done anything here for a few years, npm says 2 years since a release

Yeah, i guess so. FontAwesome does not care about their own products 😅 So if someone readnig this avoid and go with some other icon library instead.

**Comment by robmadole** [comment]
We'll try and get this fixed up in the next release. It takes a full release of Font Awesome for these and those take a little bit of planning.

Thanks for reporting it.

**Comment by rivaridley** [comment]
Thanks @robmadole for your response and prioritizing a fix for this in the next release.

Can you share an idea of when the next release will happen? My team will be waiting for this to upgrade to kits, as workarounds to ignore the error have been unsuccessful. We don't want to remove type check, and can't successfully ignore this file since its being referenced in our project. If you have any suggestions to unblock in the meantime, they would be appreciated.

**Comment by rivaridley** [comment]
@robmadole I see there was a new release for font-awesome a couple days ago, but a fix for this doesnt seem to be included(?) Is there still plans to fix this issue? Or any suggestions you have for a workaround are appreciated. Thank you

**Comment by sthota-fms** [comment]
@robmadole +1, having the same issue. Please provide a workaround.

**Comment by niborium** [comment]
@robmadole i mean it's just remove 2 lines of code. Estimated time for a developer: 5 seconds. It's no rocket science.

**Comment by robmadole** [comment]
@rivaridley we didn't have a chance to get this included in the 6.5.2 release so we'll work on this for the next one.

@sthota-fms we haven't identified a workaround at this time.

@niborium the fix is 2 lines but testing takes time. Since Font Awesome is a mature and widely used product we don't skip this important step.

I'm closing this issue as @rivaridley opened another one in the main [Font-Awesome repo](https://github.com/FortAwesome/Font-Awesome/issues/20193) so we'll work on it there. This fix is not specific to react-fontawesome.

**Comment by robmadole** [comment]
We've got this released and it's available for testing.

You'll need to go into your Kit and make some kind of change that kicks off a package build and publishing. You can add and then remove an icon, or add then remove a style. Both of those should do it.

Let me know what you find, if it fixes things for you, or if there are more questions.

Sorry this one took so long. We learned a LOT about .tsconfig files during this.
